apiVersion: v1
kind: Service
metadata:
  namespace: stdelval
  name: backend-api-service
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stdelval
  name: backend-api-deployment
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: sengsathit/brief-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ROOT_PATH
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-root-path
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-password
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-name
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-database-configmap
              key: database_url