apiVersion: v1
kind: Service
metadata:
  namespace: stdelval
  name: backend-database-service
  labels:
    app: backend-database
spec:
  selector:
    app: backend-database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stdelval
  name: backend-database-deployment
  labels:
    app: backend-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-database
  template:
    metadata:
      labels:
        app: backend-database
    spec:
      containers:
      - name: backend-database
        image: sengsathit/brief-mysql:latest
        ports:
        - containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -h localhost -u root -p"$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-name

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: database-pvc