apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stdelval
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi